server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  resolver 127.0.0.11 valid=10s ipv6=off;
  set $rstmanager_api planning-service:8080;

  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location = /api {
    proxy_pass http://$rstmanager_api;
  }

  location /api/ {
    proxy_pass http://$rstmanager_api;
  }

  location = /docs {
    proxy_pass http://$rstmanager_api;
  }

  location /docs/ {
    proxy_pass http://$rstmanager_api;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
